#!/bin/sh

OLDIARY_DIR="${HOME}/.oldiary"
YEAR=`date +%Y`
MONTH=`date +%m`
DAY=`date +%d`

mkdir -p ${OLDIARY_DIR}

set_date () {
    case $1 in
        "today")
            ;;
        "yesterday")
            YEAR=`date -d yesterday +%Y`
            MONTH=`date -d yesterday +%m`
            DAY=`date -d yesterday +%d`
            ;;
        [0-9]*/[0-9]*/[0-9]*)
            YEAR=`echo $1 | cut -d "/" -f 1`
            MONTH=`echo $1 | cut -d "/" -f 2`
            DAY=`echo $1 | cut -d "/" -f 3`
            ;;
        *)
            echo "Parse failed from '$1'"
            exit -1
            ;;
    esac
}

case $1 in
    "add")
        mkdir -p ${OLDIARY_DIR}/${YEAR}/${MONTH}
        echo $2 >> ${OLDIARY_DIR}/${YEAR}/${MONTH}/${DAY}.txt
        ;;
    "list")
        if [ $2 ]; then
            set_date $2
        fi
        if [ -e ${OLDIARY_DIR}/${YEAR}/${MONTH}/${DAY}.txt ]; then
            less -N ${OLDIARY_DIR}/${YEAR}/${MONTH}/${DAY}.txt
        else
            echo "No diaries on ${YEAR}/${MONTH}/${DAY}."
        fi
        ;;
    "remove")
        if [ $2 -gt `cat ${OLDIARY_DIR}/${YEAR}/${MONTH}/${DAY}.txt | wc -l` ]; then
            echo "The diary of ${YEAR}/${MONTH}/${DAY} is less than $2 lines."
            return
        else
            REMOVED=`head -n $2 ${OLDIARY_DIR}/${YEAR}/${MONTH}/${DAY}.txt | tail -n 1`
            sed -i -e "$2,$2d" ${OLDIARY_DIR}/${YEAR}/${MONTH}/${DAY}.txt
            echo "Remove '${REMOVED}' successfully"
        fi
        ;;
esac
